blogposts/urls.py
from . import views
from django.urls import path

app_name = "blogposts"

urlpatterns = [
    path("create/", views.CreatePostView.as_view(), name="create"),
    path("", views.ListPostView.as_view(), name="list"),
    path(
        "list/<str:author>/<int:author_id>/<slug:slug>/",
        views.DetailPostView.as_view(),
        name="detail",
    ),
    path(
        "<str:author>/<int:author_id>/",
        views.UserDetailListPostView.as_view(),
        name="user_post_list",
    ),
    path(
        "update/<str:author>/<int:author_id>/<slug:slug>/",
        views.UpdatePostView.as_view(),
        name="update",
    ),
    path(
        "delete/<int:author_id>/<slug:slug>/",
        views.DeletePostView.as_view(),
        name="delete",
    ),
]

problog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('blogposts.urls', namespace='blogposts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogposts/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager

# Create your models here.


def image_path(_, filename):
    extension = filename.split(".")[-1]
    unique_id = uuid.uuid4().hex
    new_file_name = unique_id + "." + extension
    new_file_name = f"{str(_.publish)}/{str(_.author)}/{new_file_name}"
    return "post/" + new_file_name


class PublishedPost(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to=image_path, null=True, blank=True)
    slug = models.SlugField(max_length=250, editable=True, null=True, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts",
        default=1,
    )
    body = RichTextField()
    publish = models.DateField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    objects = models.Manager()  # The default manager.
    published = PublishedPost()  # Our custom manager.
    tags = TaggableManager()  # For managing tag
    count = models.IntegerField(default=0)

    class Meta:
        ordering = ("-publish",)
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title + str(self.id))
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    @staticmethod
    def draft():
        return Post.objects.all().filter(status="draft")

    def get_absolute_url(self):
        return reverse(
            "blogposts:user_post_list",
            kwargs={
                "author": self.author.username,
                "author_id": self.author.id,
            },
        )


class Comment(models.Model):
    email = models.EmailField(max_length=150)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_comments",
        null=True,
        blank=True,
    )
    comment_content = models.TextField(verbose_name="comment")
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comment_post",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return "" + self.email or "" + " " + self.user or ""

    def get_absolute_url(self):
        return reverse(
            "blogposts:detail",
            kwargs={
                "author": self.post.author.username,
                "author_id": self.post.author.id,
                "slug": self.post.slug,
            },
        )

blogposts/forms.py
from django import forms
from .models import Post, Comment
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = (
            "title",
            "image",
            "body",
            "status",
            "tags",
        )
        required = {"author": False}

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({"class": "form-control"})

    def save(self, commit=True, *args, **kwargs):
        obj = super(PostForm, self).save(commit=False, *args, **kwargs)

        from django.utils.text import slugify

        obj.slug = slugify(obj.title)
        if commit:
            obj.save()
        return obj


class PostCreateForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = (
            "title",
            "author",
            "image",
            "body",
            "status",
            "tags",
        )

    def __init__(self, *args, **kwargs):
        super(PostCreateForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({"class": "form-control px-3"})
        self.fields["author"].widget.attrs.update({"style": "display:none;"})
        self.fields["author"].label = ""


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            "email",
            "user",
            "comment_content",
            "post",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs.update({"class": "form-control"})
        self.fields["user"].widget.attrs.update({"style": "display:none;"})
        self.fields["user"].label = ""
        self.fields["post"].widget.attrs.update({"style": "display:none;"})
        self.fields["post"].label = ""

blogposts/views.py
from taggit.models import Tag
from django.db.models import Q
from django.http import Http404
from django.conf import settings
from .models import Post, Comment
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from .forms import PostForm, PostCreateForm, CommentCreateForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import (
    ModelFormMixin,
    DeleteView,
    DeletionMixin,
    BaseDetailView,
    View,
)


class ListPostView(ListView):
    model = Post
    template_name = "blogposts/common_list.html"
    context_object_name = "objects"

    def get_queryset(self, *args, **kwargs):
        queryset = super(ListPostView, self).get_queryset(*args, **kwargs)
        queryset = queryset.filter(status="published")
        query = self.request.GET.get("q")
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query)
                | Q(body__icontains=query)
                | Q(author__username=query)
                | Q(tags__name=query)
            )
            queryset = (
                queryset.order_by("-created").filter(status="published").distinct()
            )

        page = self.request.GET.get("page", 1)
        paginator = Paginator(queryset, 4)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(ListPostView, self).get_context_data(*args, **kwargs)
        # filtering similar tagged post
        tag = []
        for obj_tag in Tag.objects.all().order_by("name"):
            tag.append(str(obj_tag.name))
        tag = set(tag)  # eleminates dublicates
        tag = list(tag)  # back to list
        tag = sorted(tag)  # sorting
        context["tags"] = tag
        context["featured"] = Post.published.all().order_by("-count")[:5]
        context["users"] = User.objects.all()[:5]
        context["page_obj"] = context["objects"]

        return context


class UserDetailListPostView(DetailView):
    model = Post
    template_name = "blogposts/user_list.html"
    context_object_name = "objects"
    pk_url_kwarg = "author_id"
    slug_url_kwarg = "author"

    def get_queryset(self, *args, **kwargs):
        queryset = super(UserDetailListPostView, self).get_queryset(*args, **kwargs)

        query = self.request.GET.get("q")
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query)
                | Q(body__icontains=query)
                | Q(author__username=query)
                | Q(status=query)
            ).distinct()
            queryset = queryset.order_by("-created")

        if not self.request.user.is_authenticated:
            queryset = queryset.filter(status="published")
            queryset = queryset.order_by("-created").distinct()
            print(queryset)

        return queryset

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg)  # author_id
        slug = self.kwargs.get(self.slug_url_kwarg)  # author_username
        if pk is not None and slug is not None:
            queryset = queryset.filter(author__id=pk).filter(author__username=slug)
            print(queryset, "bibek")

        try:

            page = self.request.GET.get("page", 1)
            paginator = Paginator(queryset, 4)
            try:
                queryset = paginator.page(page)
            except PageNotAnInteger:
                queryset = paginator.page(1)
            except EmptyPage:
                queryset = paginator.page(paginator.num_pages)
            obj = queryset
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailListPostView, self).get_context_data(*args, **kwargs)
        pk = self.kwargs.get(self.pk_url_kwarg)
        user = get_object_or_404(User, pk=pk)
        context["user"] = user
        print(self.queryset)
        context["page_obj"] = self.get_object()
        user_posts_count = user.blog_posts.all()
        if self.request.user.username == user.username:
            context["counts"] = user_posts_count.count()
        else:
            context["counts"] = user_posts_count.filter(status="published").count()
        return context


class CreateCommentView(SuccessMessageMixin, CreateView):
    template_name = "blogposts/details.html"
    form_class = CommentCreateForm
    success_message = "Post was created SuccessFully"

    def form_valid(self, form):
        form.save(commit=False)
        slug = self.kwargs.get(self.slug_url_kwarg)
        form.instance.user = self.request.user
        form.save()
        return super(CreateCommentView, self).form_valid(form)


class DetailPostView(DetailView, SuccessMessageMixin, CreateView):
    model = Post
    # form_class = PostCreateForm
    context_object_name = "objects"
    slug_url_kwarg = "slug"
    pk_url_kwarg = "author_id"
    author_url_kwarg = "author"
    template_name = "blogposts/detail.html"
    form_class = CommentCreateForm
    success_message = "Commented SuccessFully"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg)  # author_id
        slug = self.kwargs.get(self.slug_url_kwarg)
        author = self.kwargs.get(self.author_url_kwarg)  # author_username
        if pk is not None and slug is not None and author is not None:
            queryset = (
                queryset.filter(author__id=pk)
                .filter(author__username=author)
                .filter(slug=slug)
            )
            print(queryset, "bibek")

        if pk is None and slug is None and author is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )

        try:
            obj = queryset.get()
            obj.count = obj.count + 1
            obj.save()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj

    def form_valid(self, form):
        form.save(commit=False)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
        form.instance.post = Post.objects.filter(slug=slug).first()
        form.save()
        return super(DetailPostView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(DetailPostView, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get(self.slug_url_kwarg)
        comments = (
            Comment.objects.filter(post=Post.objects.filter(slug=slug).first())
            .order_by("created_at")
            .distinct()
        )
        context["comments"] = comments
        return context


@method_decorator(login_required(login_url="/accounts/login/"), name="dispatch")
class CreatePostView(SuccessMessageMixin, CreateView):
    template_name = "blogposts/create.html"
    form_class = PostCreateForm
    success_message = "Post was created SuccessFully"

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user
        form.save()
        form.save_m2m()
        return super(CreatePostView, self).form_valid(form)


@method_decorator(login_required(login_url="/accounts/login/"), name="dispatch")
class UpdatePostView(SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    slug_url_kwarg = "slug"
    pk_url_kwarg = "author_id"
    author_url_kwarg = "author"
    template_name = "blogposts/update.html"
    success_message = "Post was Updated successfully"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get(self.pk_url_kwarg)  # author_id
        slug = self.kwargs.get(self.slug_url_kwarg)
        author = self.kwargs.get(self.author_url_kwarg)  # author_username
        if pk is not None and slug is not None and author is not None:
            queryset = (
                queryset.filter(author__id=pk)
                .filter(author__username=author)
                .filter(slug=slug)
            )
            print(queryset, "bibek")

        if pk is None and slug is None and author is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )

        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(

templates/blogposts/create.html
{% extends 'base.html' %}
{% block title %}
Create Post

{% endblock %}
{% block content %}
<div class="row">
  <div class="container">
    <div
      class="col-md mt-5 mx-auto justify-content-center align-items-center"
    >
      <div class="m-5 shadow p-5 text-dark">
        <h1>Create a Post</h1>
        <p>Please, use the following form to log-in:</p>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
  
          <input class="btn btn-secondary px-5" type="submit" value="Create" />
        </form>
        </p>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blogposts/update.html
{% extends 'base.html' %}
{% block title %}
Update

{% endblock %}
{% block content %}
<div class="row">
  <div class="container">
    <div
      class="col-md mt-5 mx-auto justify-content-center align-items-center"
    >
      <div class="m-5 shadow p-5 text-dark">
        <h1>Update a Post</h1>
        <p>Please, use the following form to log-in:</p>

        <form class="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{form.media}} {{form.as_p}}
  
          <input class="btn btn-secondary px-5" type="submit" value="Update" />
        </form>
        </p>
      </div>
    </div>
  </div>
</div>



{% endblock %}

templates/blogposts/user_list.html

{% extends 'base.html' %}
{% block title %}
{{ request.user.email }} Posts

{% endblock %}

{% block content %}
    {% include 'partials/alert.html' %}
{% include 'partials/jumbotron.html' with status=user  %}
<div class="row my-2">
  <div class="offset-1 col-3 mt-3">

    <div class="card sticky-top bg-light shadow-lg">
      <img
        width="100px"
        height="200px"
        class="card-img-top rounded-circle p-4"
        src="{% if  user.profile.photo %}/media/{{user.profile.photo}}{% else %}/static/img/anonymous.png{% endif %}"
        alt="{{user.email}}"
      />
      <div class="card-body">
        <h5>Author of this posts:</h5>
        <div class="border-bottom border-warning"></div>
        <p  class="lead">{% if user.first_name %} 
          {{user.first_name|capfirst}} {{user.last_name|capfirst}}  
          {% else %} {{user.email}} {% endif %}</p>
        
        <h5>Bio:</h5>
        <div class="border-bottom border-warning"></div>
        <p  class="text-justify">{% if user.profile.bio %}
           {{user.profile.bio}} {% else %} --- {% endif %}</p>
        
           <h5>Profession:</h5>
           <div class="border-bottom border-warning"></div>
        <p  class="lead">{% if user.profile.profession %}{{user.profile.profession}} {% else %} --- {% endif %}</p>
      <h5>Total Posts:</h5>
      <div class="border-bottom border-warning"></div>
     <p  class="lead">{% if counts %}{{counts}} {% else %} --- {% endif %}</p>
      </div>
    </div>
  </div>
  <div class="col-8">
    
    {% for obj in objects %}
    <div class="card shadow bg-light d-inline-block m-3" style="width: 22rem;">
      <div class="card-header text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-pencil-square"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
          />
          <path
            fill-rule="evenodd"
            d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
          />
        </svg>
        {{obj.author}}
        <li class="float-right list-unstyled">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-clock"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm8-7A8 8 0 1 1 0 8a8 8 0 0 1 16 0z"
          />
          <path
            fill-rule="evenodd"
            d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5z"
          />
        </svg>
        {{obj.created|date}}</li>
      </div>
      <img
        width="300px"
        height="200px"
        src="/media/{{ obj.image }}"
        class="card-img-top"
        alt="..."
      />
      <div style="height: 8rem;" class="card-body">
        <h6 class="card-title text-justify">{{ obj.title|truncatewords:5 }}</h6>
        <br>
        <a
          href="{% url 'blogposts:detail' author=obj.author author_id=obj.author.id slug=obj.slug %}"
          class="btn btn-secondary"
          >Read More...</a
        >
        {% if obj.author.id is request.user.id %}
        <a
        href="{% url 'blogposts:update' author=obj.author author_id=obj.author.id slug=obj.slug %}"
        class="btn btn-secondary"
        >Update</a>
        <a
        href="{% url 'blogposts:delete'  author_id=obj.author.id slug=obj.slug %}"
        class="btn btn-secondary"
        >delete</a>
        {% endif %}
      </div>
      <div class="card-footer text-dark bg-light">
        <svg
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-eye-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
          <path
            fill-rule="evenodd"
            d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
          />
        </svg>
       <h5 class="badge badge-secondary">{{obj.count}}</h5> 
        <li class="float-right list-unstyled">
        <svg
          class="text-right"
          width="1em"
          height="1em"
          viewBox="0 0 16 16"
          class="bi bi-tags-fill"
          fill="currentColor"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 7.586 1H3zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"
          />
          <path
            d="M1 7.086a1 1 0 0 0 .293.707L8.75 15.25l-.043.043a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 0 7.586V3a1 1 0 0 1 1-1v5.086z"
          />
        </svg>
        {% for tag in obj.tags.names %}
     {{tag }}
        {% endfor %}
      </div></li>
    </div>
    {% empty %}
    <div class="d-flex pt-5 justify-content-center align-items-center">
      <p class="bg-warning mt-5 p-5 shadow h1 text-danger">User have no post</p>
    </div>
   
    {% endfor %}
    {% if page_obj.has_other_pages %}
     <br>
     <nav  class="d-flex justify-content-center "  aria-label="...">
     <ul class="pagination ">
       {% if page_obj.has_previous %}
         <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
       {% else %}
         <li class="page-item "><span class="page-link">Previous</span></li>
       {% endif %}
       {% for i in page_obj.paginator.page_range %}
         {% if page_obj.number == i %}
           <li  class="page-item active"><span class="page-link">{{ i }} <span class="page-link sr-only">(current)</span></span></li>
         {% else %}
           <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
         {% endif %}
       {% endfor %}
       {% if page_obj.has_next %}
         <li class="page-item"><a class="page-link"  href="?page={{ page_obj.next_page_number }}">Next</a></li>
       {% else %}
         <li class="page-item "><span class="page-link">Next</span></li>
{% endif %}
</ul>
</nav>
{% endif %}
  </div>
</div>

{% endblock %}